### ISSUE TITLE
RAT page returns Internal Server Error

### ISSUE THREAD

**Issue by tannerbk** [snoplus/minard#168] opened 2018-07-03 23:03 UTC
We've stopped running the ANALYSIS job on the nearline as of run 115111 so that might be related.

**Comment by tlatorre-uchicago** [comment] 2018-07-03 23:11
Do you know if it's gone for good or is it coming back?

**Comment by tannerbk** [comment] 2018-07-03 23:13
Not sure, we've just stopped running it nearline since I don't think anyone uses it or is responsible for maintaining it and it was quite slow. I could see someone picking it back up for scintillator.

**Comment by tlatorre-uchicago** [comment] 2018-07-03 23:34
Huh, well I wasn't able to reproduce it locally and then I just restarted the web server and it started working again. No idea what could have caused this. I'm going to close now, but we can reopen this if it happens again.

**Comment by tannerbk** [comment] 2018-07-06 14:07
This is still an issue for me.

**Comment by tlatorre-uchicago** [comment] 2018-07-06 16:04
I've put in some code to return the exception if it happens again. Hopefully that will give some indication as to what is the problem since I'm not able to reproduce it running locally.

**Comment by tannerbk** [comment] 2018-07-09 14:56
![rat_page_500_internal_server_error](https://user-images.githubusercontent.com/2319312/42457932-b2ad9798-8366-11e8-9798-b457153f48a8.png)

**Comment by tlatorre-uchicago** [comment] 2018-07-09 15:19
So, the problem is that the nearline_monitoring_summary view is modifying the RUN_TYPES list used in nlrat here: https://github.com/snoplus/minard/blob/063a9918a59af912f55f66af24224d019357c086/minard/views.py#L1315 and here: https://github.com/snoplus/minard/blob/063a9918a59af912f55f66af24224d019357c086/minard/views.py#L584.

It's adding a key with -1 which then causes an exception when the nlrat module tries to bitshift the run type here: https://github.com/snoplus/minard/blob/master/minard/nlrat.py#L30.

**Comment by tlatorre-uchicago** [comment] 2018-07-16 22:59
Fixed in #171

**Closed by tlatorre-uchicago** 2018-07-16 22:59 UTC
